# Generated by Django 2.2.6 on 2019-10-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedentry',
            options={'verbose_name_plural': 'Feed entries'},
        ),
        migrations.CreateModel(
            name='FeedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=250)),
                ('entry', models.TextField()),
                ('updated', models.DateTimeField()),
                ('feed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_of', to='feed.FeedSource')),
            ],
        ),
        migrations.AddField(
            model_name='feedsource',
            name='feed',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed.FeedInfo'),
        ),
    ]
