# Generated by Django 2.2.6 on 2019-10-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191029_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedinfo',
            options={'verbose_name_plural': 'Feed info'},
        ),
    ]
