# Generated by Django 2.2.6 on 2019-10-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20191029_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsource',
            name='feed',
        ),
    ]
