# Generated by Django 2.2.6 on 2019-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_feedsource_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedentry',
            name='guid',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
